### PR TITLE
Name of images to improve SEO

### PR DESCRIPTION
**Pull request by Huvik**
Hey, how i proposed in #7 i added name in path to improve indexing of images.

But i am not sure how to test it, so i am open to some advices. This PR is work in progress.

### CODE REVIEW

**Comment by schickling** [comment]
Thanks for the PR. I think something like the following should also be possible:

```
/v1/ciwkuhq2s0dbf0131rcb3isiq/cj37jinmt008o0108zwhax711/Graphcool.jpg
/v1/ciwkuhq2s0dbf0131rcb3isiq/cj37jinmt008o0108zwhax711/600x200/Graphcool.jpg
/v1/ciwkuhq2s0dbf0131rcb3isiq/cj37jinmt008o0108zwhax711/600x200/20x20/Graphcool.jpg
```

**Comment by Huvik** [comment]
Okey, so i will fix it. Because i tough that when its image proxy you have to change image somehow not only serve it with name. And what about testing?

**Comment by schickling** [comment]
I think it should be easy enough to write some tests for the `parseParams` function using [ava](https://github.com/avajs/ava)

**Comment by schickling** [comment]
Could you please rebase from master to apply the latest changes?

**Comment by Huvik** [comment]
Sure :)

**Comment by schickling** [comment]
Great. Could you please also add the `fileName` to the `Params` object + type?

**Comment by Huvik** [comment]
Sure, but what is purpose of that? Only for testing? Because there is no usage for it after that or I am missing something?

**Comment by schickling** [comment]
You're completely right! Great job! 💪

**Pull request merged**
